### ISSUE TITLE
Timeslider: fixes/tweaks

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#428]
- [x] in single data view, center the date above the handle
- [x] in compare mode
  - move the top date (for the left globe) to the left of the handle and align right with the handle
  - move the bottom date (for the right globe) to the right of the handle and align left with the handle
- [x] move the min/max dates between the two rails in compare mode
- [x] adjust colors of the track and the data points to closer match the designs in figma:

![image](https://user-images.githubusercontent.com/2733607/89770651-5bce8c00-daff-11ea-9183-bec25120cae5.png)

**Comment by pwambach** [comment]
I didn't build the green current range selection because most of the layers we have so many timesteps that a range is only 1 pixel wide so there is no visual range. Instead I upscaled the current ticks a bit so that you can better see which one is active.
![Screenshot 2020-08-12 at 10 59 34](https://user-images.githubusercontent.com/1611635/89996318-eee7fd00-dc8a-11ea-884a-8b99e425f23d.png)

Also the gray text colors are not readable in front of the gray globe. Using white now.
