### ISSUE TITLE
Stories: Improve image display

### ISSUE THREAD

**Issue by pmast** [ubilabs/esa-climate-from-space#838]
- [ ] add captions to side-by-side view
- [ ] add support for long captions (up to 5 lines)
- [ ] add support for headlines to captions (markdown?!)
- [ ] captions: adjust style to improve readability (size, contrast, …)
- [ ] full-screen images: take as much screen size as possible
- [ ] feedback pagination arrows are often overlooked, people miss other images (improve visibility, automatic cycling, thumbnails)
- [ ] make the captions being stored as markdown. Restrict the markdown support to headlines and links, definitely no images!

**Comment by pmast** [comment]
Example for improvement for display cover in side-by-side view:
![image](https://user-images.githubusercontent.com/2733607/109436194-b806e800-7a1e-11eb-97f3-9d16f444bde5.png)

**Comment by pmast** [comment]
Example for larger image sin full screen mode:
![image](https://user-images.githubusercontent.com/2733607/109436237-da990100-7a1e-11eb-9a88-61b73cc520e5.png)

**Comment by elenamuxui** [comment]
Font: 
 - Headline: Arial, 13px, bold. 
 - Captions: Arial, 13px (Instead of 11px), regular. 

![01](https://user-images.githubusercontent.com/63637901/109633969-00222980-7b49-11eb-9010-f23e2dc42229.png)
![02](https://user-images.githubusercontent.com/63637901/109633961-fef0fc80-7b48-11eb-96cf-abfc5cd0bf55.png)
![03](https://user-images.githubusercontent.com/63637901/109634146-2fd13180-7b49-11eb-9d1d-c796835e1d60.png)
